// Assemble src-tauri/scripts/init.js from skin sources:
//   skin/skin.css  -> SKIN_CSS
//   skin/fonts/*.woff2 -> FONTS (base64)
//   skin/skin.js   -> inline logic
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const skinDir = join(root, "skin");
const outDir = join(root, "src-tauri", "scripts");
const distFontsDir = join(root, "dist", "fonts");
mkdirSync(outDir, { recursive: true });
mkdirSync(distFontsDir, { recursive: true });

const css = readFileSync(join(skinDir, "skin.css"), "utf8");
const logic = readFileSync(join(skinDir, "skin.js"), "utf8");

const fonts = {};
for (const file of readdirSync(join(skinDir, "fonts"))) {
  if (!file.endsWith(".woff2")) continue;
  const name = file.replace(/\.woff2$/, "");
  const bytes = readFileSync(join(skinDir, "fonts", file));
  fonts[name] = bytes.toString("base64");
  // The splash page references the same fonts as local files.
  writeFileSync(join(distFontsDir, file), bytes);
}

const banner =
  "/* AUTO-GENERATED by scripts/build-skin.mjs — do not edit. */\n";

const output =
  banner +
  `(function () {\n` +
  `"use strict";\n` +
  `const FONTS = ${JSON.stringify(fonts)};\n` +
  `const SKIN_CSS = ${JSON.stringify(css)};\n` +
  logic +
  `\n})();\n`;

writeFileSync(join(outDir, "init.js"), output);
console.log(`init.js written: ${(output.length / 1024).toFixed(1)} KB`);
